tarides/dune-release

- bin/bistro.ml
- bin/cli.ml
- bin/cli.mli
- bin/distrib.ml
- bin/opam.ml
- bin/publish.ml
- bin/status.ml
- lib/archive.ml
- lib/pkg.ml
- lib/pkg.mli
- lib/vcs.ml
/cc @diml 
I've done a minimal amount of testing with sexplib0 with `dune-release distrib --keep-v` and `dune-release opam --keep-v` and that seems to work fine.
>  Add a --keep-v option to not drop `v` at the beginning of version numbers

- bin/bistro.ml
- bin/cli.ml
- bin/cli.mli
- bin/distrib.ml
- bin/lint.ml
- bin/log.ml
- bin/opam.ml
- bin/publish.ml
- bin/tag.ml
- lib/archive.ml
- lib/archive.mli
- lib/github.ml
- lib/github.mli
- lib/opam.ml
- lib/opam.mli
- lib/pkg.ml
- lib/pkg.mli
- lib/sos.ml
- lib/sos.mli
- lib/vcs.ml
- lib/vcs.mli
This allow to see what the tool will do before doing it.
Related to #17 (/cc @Drup)
It pretty useful to debug too, as it allows to play with the tools without being afraid of pushing/deleting the wrong stuff.
> Add a --dry-run option to all commands

- bin/tag.ml
- lib/github.ml
- lib/pkg.ml
- lib/pkg.mli
- lib/vcs.ml
- lib/vcs.mli
Instead, just force-push the latest tag to the dev-repo. Force-pushing
is probably not what we want here, but that's already an improvement.
> publish: do not force push all the tags to a random repo

- lib/opam.ml
- lib/opam.mli
- lib/pkg.ml
> lint: don't use new --warn CLI options when running opam 1.2.2

- bin/cli.ml
- bin/opam.ml
- lib/pkg.ml
This reverts e4bd7ad. The change is safe to do now as their is no
'browse' command anymore.
> Use '-p' instead of '-n' to follow dune conventions

- bin/opam.ml
- dune-release.opam
- lib/github.ml
- lib/github.mli
- tests/jbuild
- tests/test_github.ml
- tests/tests.ml
When running `dune-release opam submit`, the actual PR creation on `opam-repository` can fail due to an invalid `head` field in the API requests. As far as I understand, this appears to happen when the user or organisation owning the package repo differs from the `opam-repository` fork owner. See #60 for further details.
Since `dune-release opam submit` knows the `opam-repository` fork URI, it can be used to determine the owner of the fork and pass it in the github API request instead of the package repository owner.
This is a first draft, I mostly wanted to have your feedback on the fix.
I wasn't sure whether HTTP URIs should be supported along with SSH ones here but that should be fairly easy to add.
If the parsing of the URI fails it falls back to `user`.
You'll also note I added some …
>  Determine opam-repository fork user from URI

- lib/github.ml
- tests/test_github.ml
Accept urls without .git at the end
> Fix github url regexp

- lib/distrib.ml
Backport https://github.com/dbuenzli/topkg/commit/6cf1eaec24a6b28ee8ab8829d43d74542e7a17d9
Fix #103
> Add .ps and .eps files to default files excluded from watermarking

- lib/opam.ml
This situation can happen when reorganizing Dune / opam packages and
it is helpful to have a proper error message.
Signed-off-by: Emilio Jesus Gallego Arias <e@x80.org>
> [opam] Remove assert false in favor of error message.

- bin/opam.ml
- dune-release.opam
- lib/dune
- lib/opam.ml
- lib/opam.mli
use opam-core for doing these operations. instead of generating an URL and
checksum string (and parse with OpamFile.URL.read_from_string), construct a
OpamFile.URL.t directly in Opam.URL.with_distrib_file.
since dune-release always generates opam2 files, I don't see any reason to embed the md5 checksum in there at all...
> generate sha256 and sha512 checksums for release

- lib/pkg.ml
`opam lint` doesn't mind doc fields without trailing slashes, so it seems to me that `dune-release` shouldn't either.
> handle doc fields with no trailing slash

- lib/pkg.ml
> embed a 'version: "$release-version"' in each opam file of the current directory when building an archive

- lib/github.ml
- lib/sos.ml
- lib/sos.mli
I believe this should fix #117, and fix #114 as well.
What happened is that the hand-rolled `cp` function in `Github.publish_in_git_branch` would not work if the `doc/` directory did not already exists on the `gh-pages` branch and thus `dune-release publish doc` would fail when trying to release new packages.
See the `dune-release` logs (with a few extra debug prints of my own):
```
$ dune-release publish
fatal: Couldn't find remote ref gh-pages
Initialized empty Git repository in /tmp/gh-pages-ce3eac.tmp/.git/
Switched to a new branch 'gh-pages'
[gh-pages (root-commit) cd3c372] Initial commit by dune-release.
1 file changed, 0 insertions(+), 0 deletions(-)
create mode 100644 README
warning: no common commits
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), …
```
> Fix publish doc when no doc directory is present on gh-pages

- lib/github.ml
- lib/styled_pp.ml
- lib/styled_pp.mli
- lib/text.ml
- lib/text.mli
Missed that module during my previous work on the `publish` command logs but that's where other such formatters are defined.
> Move Styled_pp to Text.Pp

- bin/opam.ml
- lib/github.ml
- lib/opam.ml
- lib/styled_pp.ml
- lib/styled_pp.mli
- lib/text.ml
- lib/text.mli
Depends on #139 
This PR adds a few extra logs to describe the detailed steps of `opam pkg` and `opam submit` sub-commands.
It also silence some of the command being run by using `Sos.run_quiet` in a similar fashion to wha was done in #137.
This is what the output looks like (tested on top of #140):
> Add logs to describe the opam command's behaviour

- bin/opam.ml
- lib/github.ml
- lib/github.mli
- lib/opam.ml
- lib/opam.mli
I'm not sure this should be merged but it is really convenient for testing. I guess it could be useful for people maintaining custom opam repositories as well.
> Allow to submit packages to a different opam repo on github

- bin/tag.ml
- lib/prompt.ml
- lib/prompt.mli
We now ask for confirmation before creating or deleting the tag when running `dune-release tag`.
Such prompts can be skipped by passing the `-y/--yes` flag on the command line.
If this looks good to you I'll add other such prompts and CLI flags elsewhere. As a rule of thumb I'd say we should ask for confirmation before any modification of the local git tree or the remote github repo. From the top of my head that would include:
- Pushing to the gh-pages branch
- Pushing tags
- Creating a release through the github API
- Uploading an archive through the github API
- Opening a PR to the opam repository through github API
I think all the rest is done either in a tmp dir or the _build dir but I might have missed something.
> Prompt user for confirmation during tag command

- CHANGES.md
- lib/distrib.ml
- lib/distrib.mli
- lib/pkg.ml
This PR removes all watermarks substitution code from `dune-release` and relies on `dune subst` for that instead.
As `dune-release` didn't not let users sepcify custom watermarks and `dune subst` covers all the default ones with the same semantic it shouldn't be an issue, except maybe for some binary file formats which aren't filtered out by `dune subst` and were by `dune-release`'s watermarking.
This will also have the nice side effect of making dune-release compatible with the generated opam workflow from `dune>=1.10`.
> Use dune subst for watermarking

- CHANGES.md
- lib/github.ml
Fixes #155 or to be precise, fixes the bug that lead to the missing documentation. I will release a patch and a new documentation once this gets merged.
When I replaced the hand-rolled `cp` code in documentation publication I did not account for different `cp` behaviours depending on the existence of the destination directory. That means that when one wants to publish to the root of its gh-pages, the `_html` dir was copied as is in there instead of its content because the root of the gh-pages temporary project exists. This bug wasn't triggered during my tests because I published the doc in a `doc` sub dir.
> Fix documentation publication

- bin/distrib.ml
- bin/opam.ml
- bin/publish.ml
- bin/tag.ml
- lib/app_log.ml
- lib/app_log.mli
- lib/config.ml
- lib/delegate.ml
- lib/github.ml
- lib/lint.ml
- lib/opam.ml
- lib/prompt.ml
This fixes #159.
App level logs now go through an `App_log` module which puts headers in front of logs based on their status.
Here is an example output:
It's not so obvious without the colors but I personally tend to look at the left of the screen and it should still be more noticeable than it used to.
```
$ dune-release publish
[-] Publishing documentation
[-] Selected packages: dummy
[-] Generating documentation from _build/dummy-v0.2.0+test.tbz
[-] Publishing to github
[-] Updating local gh-pages branch
[+] No documentation changes for dummy 0.2.0+test in directory . of gh-pages branch
[-] Publishing distribution
[-] Publishing to github
[?] Push tag v0.2.0+test to git@github.com:NathanReb/dune-release-testing.git? [Y/n]
```
> Distinguish logs with a header

- CHANGES.md
- lib/opam.ml
- lib/opam.mli
- lib/pkg.ml
Fixes #164
This makes the description field optional when submitting a PR to opam-repository.
Given that opam considers it okay as long as there's a synopsis I think it make sense to allow a missing description field. We might even consider make that just a warning in the lint phase as well but that's a separate matter I'd say. The important is that it doesn't prevent one from releasing!
> Make description optional for opam submit

- CHANGES.md
- dune-project
- dune-release.opam
- lib/pkg.ml
- lib/pkg.mli
- tests/dune
- tests/test_pkg.ml
- tests/test_pkg.mli
- tests/tests.ml
Fixes #163 
The code that adds the version to the opam file before building the distrib tarball was a bit lax and in some cases (like in #163) it would filter out lines that weren't actually the version field line.
This PR adds a few tests and strengthen that part of the code a bit.
The proper fix would probably be to use opam's libary for that but I think a quick fix will do for now. We won't need to do this anymore when integrating into dune!
> Fix a bug in opam file transformation for distrib

- CHANGES.md
- lib/archive.ml
- lib/stdext.ml
- lib/stdext.mli
- replace the exceptions with error types in archive.ml
- defining a `Sbytes` module to wrap 2 unsafe functions of `Bytes`
- minor style changes (put the infix operator and the anonymous function argument at the end of the line) (applying ocamlformat would generate a huge diff for now)
> Streamline the error handling in archive.ml

- CHANGES.md
- bin/opam.ml
- lib/github.ml
- lib/github.mli
- tests/test_github.ml
Should fix #173 
- using the `user` field of the `.yaml` configuration file as the first choice, and then trying to deduce it from URI if it is not set in the configuration file.
- handling HTTPS in addition to SSH URIs
> Use the 'user' field in the configuration before inferring it from repo URI and handles HTTPS URIs

- .ocamlformat
- bin/cli.mli
- lib/app_log.mli
- lib/archive.mli
- lib/distrib.mli
- lib/github.mli
- lib/lint.mli
- lib/opam.mli
- lib/pkg.mli
- lib/prompt.mli
- lib/sos.mli
- lib/stdext.mli
- lib/text.mli
- lib/vcs.mli
- lib/xdg.mli
I was writing documentation for #197 and noticed we were not formatting those (not enabled by default because officially it's still experimental but it's working great).
No need for an entry in the changelog IMO.
> Let ocamlformat format docstrings

- CHANGES.md
- lib/config.ml
- lib/stdext.ml
- lib/stdext.mli
Fix #124
- Add a new `Stdext.Unix.read_line` function with a `echo_input` flag (only works on Unix)
- tested with `utop` (it works)
> Do not echo input characters when reading token

- CHANGES.md
- lib/vcs.ml
- lib/vcs.mli
- tests/test_vcs.ml
- tests/tests.ml
Print the executed cmd as a single string instead of a list of arguments, and add a few tests.
Should improve the situation on #122 
We could argue the tests are not necessary, remove them and remove the new function from the Vcs.mli API.
> Improve the output of VCS command errors

- CHANGES.md
- lib/lint.ml
- lib/opam.ml
- lib/opam.mli
- tests/alcotest_ext.ml
- tests/alcotest_ext.mli
- tests/test_opam.ml
- tests/tests.ml
Fix #186 
- use OpamVersion from opam-core instead of invoking `opam --version`
- don't use lazy
- use Result types instead of exceptions 
- emit a warning when opam < 2.0
- add a simple test (CI only uses opam 2.0)
> Deprecate opam 1.x and better error handling

- lib/pkg.ml
- lib/stdext.ml
- lib/stdext.mli
- tests/test_stdext.ml
This changes `Stdext.Path.find_files` to accept a list of alternative
names and adds the alternatives
- COPYING and COPYING.LESSER for license, and
- ChangeLog for changes.
My motivation for the former is the [GNU conversion for naming the license file(s)](https://www.gnu.org/licenses/gpl-howto.html).  The second is a fairly common convention which I used previously, though I don't mind if we drop it from this PR.
**Note** that the change to `find_files` breaks backwards compatibility for the library. Should we do it differently?
> Support some common alternative names for standard files.

- dune-release.opam
`samoht/dune-release` → `ocamllabs/dune-release`.
> Update GitHub organisation in opam file

- CHANGES.md
- bin/delegate_info.ml
- bin/delegate_info.mli
- bin/main.ml
- bin/publish.ml
- lib/delegate.ml
- lib/pkg.ml
- lib/pkg.mli
This new command delegate-info allows the user to obtain:
- the relative path to the tarball ("tarbal" as argument)
- the relative path to the documentation ("docdir" as argument)
- the publication message ("publication-message" as argument)
> Add new command: delegate-info

- lib/curl.ml
- lib/curl.mli
- lib/github.ml
- tests/test_curl.ml
- tests/tests.ml
Should make the review of #202 easier as we would have unit tests on the curl requests
Each commit can be reviewed independently.
> Isolate curl requests and add unit tests

- CHANGES.md
- bin/config.ml
- bin/config.mli
- bin/main.ml
- lib/config.ml
- lib/config.mli
- lib/stdext.ml
- lib/stdext.mli
Fixes #185 
This PR add a new subcommand to display and edit the global dune-release configuration, along with a bit of documentation as to what each of the fields is used for.
This should make the global config and its components more discoverable for users.
While working on this I noticed that the user field might not be of any use and that it may even cause bugs if it differs from the one in the remote opam-repo URL. We should take a look at this separately!
> Add a config subcommand to display and edit global configuration

- bin/cli.ml
- lib/archive.ml
- lib/archive.mli
- lib/config.mli
- lib/distrib.ml
- lib/distrib.mli
- lib/github.mli
- lib/opam.ml
- lib/opam.mli
- lib/pkg.ml
- lib/pkg.mli
- lib/sos.ml
- lib/stdext.ml
- lib/stdext.mli
- lib/text.ml
- lib/text.mli
- lib/vcs.ml
- lib/vcs.mli
(Spring cleaning)
Less code to browse, less `grep` results, easier to maintain.
> Removing dead code

- CHANGES.md
- bin/publish.ml
- lib/lint.ml
- lib/pkg.ml
- lib/pkg.mli
- tests/bin/no_doc/dune
- tests/bin/no_doc/run.t
> Skip documentation publication when opam's `doc` field is missing 

- lib/github_v3_api.ml
fix #175 
It reads the `message` field of the json response, this is only an internal API change for now. We still need to define which specific errors could be caught and worked around
> Allow Github_v3_api functions to handle some github errors

- lib/curl.ml
- lib/curl.mli
- lib/curl_option.ml
- lib/curl_option.mli
- lib/github.ml
- tests/bin/no_doc/run.t
- tests/lib/alcotest_ext.ml
- tests/lib/test_curl.ml
as discussed in #177 
From reading the `curl` documentation it's not obvious to me whether the `--config` option is necessary, does someone has more experience with it?
I don't think we need to add a changelog entry for this PR.
> Use long names for curl options and document their usage

- CHANGES.md
- README.md
- lib/github.ml
> The `git` command used in `publish doc` should check `DUNE_RELEASE_GIT` (even if deprecated) before `PATH` and document runtime dependencies

- CHANGES.md
- bin/bistro.ml
- bin/opam.ml
- bin/opam.mli
- tests/bin/opam-pkg-distrib-file-opt/dune
- tests/bin/opam-pkg-distrib-file-opt/run.t
- tests/bin/opam-pkg-distrib-uri-opt/dune
- tests/bin/opam-pkg-distrib-uri-opt/run.t
The option used to have lower priority than the recently introduced `url_file` which made it impossible to overwrite it if you wanted to publish the tarball to github and somewhere else but wanted to use the URL for the second one in opam.
I think it's a side effect of the `Pkg` module which contains more than it really should. We should try to fix this as we go.
Actually now that I think of it I'll add a commit that gets rid of the corresponding field in `Pkg.t` since it's not used anymore.
> Fix a couple bugs in opam pkg subcommand with --dist-file and --dist-uri

- CHANGES.md
- lib/archive.ml
- lib/archive.mli
- lib/vcs.ml
- lib/vcs.mli
Trying to fix the `dune-release: [ERROR] Could not parse timestamp from "1596471536": int_of_string` errors we get on debian-10-4.10_arm32 and debian-10-4.10_x86_32
> Use int64 for timestamps

- .github/workflows/main.yml
This PR adds a github action to check that the changelog has been updated unless the `no changelog` label is added.
Thanks to @emillon for working on this!
> Add @emillon's changelog check action

- CHANGES.md
- bin/distrib.ml
- lib/pkg.ml
- lib/pkg.mli
- tests/bin/no_doc/run.t
Fixes #244
They used to only run for the main package in multi-opam repos.
> Build and run tests for all selected packages in distrib

- README.md
This confused users in the past so it'd be better to clarify it in the README.
> Mention that dune-release only supports annotated tags

- CHANGES.md
- bin/tag.ml
- tests/bin/tag/run.t
> Attach the changelog to the annotated tag message

- bin/opam.ml
- bin/opam.mli
- bin/publish.ml
- lib/config.ml
- lib/delegate.ml
- lib/delegate.mli
- lib/github.ml
- lib/github.mli
- lib/lint.ml
- lib/pkg.ml
- lib/pkg.mli
- tests/lib/test_tags.ml
Should not change the behavior of dune-release:
- remove `distrib_uri` field from `Pkg.t` type
- remove `?distrib_uri` arg from `Pkg.v` function
- remove `?raw` arg from `Pkg.distrib_uri` function
- ~add `?uri` arg to `Pkg.distrib_uri` function~
- ~add `?uri` arg to `Pkg.distrib_user_and_repo` function~
- pass `?distrib_uri` arg to functions calling one of these two functions
- ~split `Pkg.distrib_uri` into `Pkg.infer_distrib_uri` and `Pkg.normalize_distrib_uri`~
- rename `Pkg.distrib_uri` to `Pkg.infer_distrib_uri`
> Sanitize usage of distrib_uri

- CHANGES.md
- lib/github.ml
Fix #280
No diff in the tests since we only use dry-mode to not submit pull requests and so on.
> Log curl calls on debug

- CHANGES.md
- lib/github.ml
- lib/prompt.ml
- lib/prompt.mli
> Try to publish the release asset again after it failed

- CHANGES.md
- bin/help.ml
- bin/publish.ml
- lib/deprecate_delegates.ml
This commit deprecates the use of delegates and publishing artefacts other than the distribution archive or the documentation, since those functionalities will be removed in the next major release. Deprecating delegates is point 3. of #188.
In order to remove delegates, we'll have to 
- remove the modules `Deprecate_delegates` and `Delegate`
- follow the provoked compile errors
- get rid of the delegate structure in `Pkg` 
- think about where to check if the user is using something else than github (provided in the opam `doc:` or `homepage:` field) to let them know early that dune-release doesn't support that. Maybe through the linter?
> Deprecate delegates

- bin/bistro.ml
- bin/cli.ml
- bin/cli.mli
- bin/distrib.ml
- bin/lint.ml
- bin/opam.ml
- bin/publish.ml
- bin/tag.ml
We're using this trick from @CraigFe in duniverse and I thought it'd be a good idea to use it here as well, especially considering the number of args some commands have.
> Wrap cmdliner arguments with variants to prevent args order mistakes

- lib/distrib.ml
- lib/distrib.mli
- lib/pkg.ml
- lib/pkg.mli
This used to rely on Distrib.t which was in fact never instantiated to anything than the default value. This simplifies this module to a static list of paths to exclude for now.
Eventually we'll move some `Pkg` functions there but for now I mostly wanted to get rid of all the indirections.
> Simplify distrib tarball preparation

- CHANGES.md
- lib/archive.ml
- tests/bin/include-versioned-dotfiles/dune
- tests/bin/include-versioned-dotfiles/run.t
`Bos.OS.Dir.fold_contents` behaviour though following its spec is very counter intuitive since specifying `~dotfiles:true` will only include dotfiles and folders in subdirectories.
Luckily this hasn't broken anything yet but it is obviously a bad behaviour that needed fixing. The fact that we maintain an explicit
list of files and folders to exclude from the archive, some of which are root dotfiles and folders confirms that this behaviour was not intentional.
> Fix a bug excluding all root dotfiles from the generated distrib tarball

- CHANGES.md
- lib/distrib.ml
Those special rules resulted in removing versioned files in the archive. There's no need for special treatment of build dirs since those shouldn't be versioned anyway and therefore won't be included in the archive since we go through a clone and a checkout before building the tarball.
> Include versioned files to the archive

- tests/bin/no_doc/run.t
   
It seems like the `no-doc`-test isn't fully deterministic. This commit
adds a couple of ellipses that are necessary for it to pass on some
environments.
> Add more ellipses to the `no-doc` cram test

- CHANGES.md
- lib/github.ml
- lib/github.mli
- lib/pkg.ml
- lib/pkg.mli
- lib/vcs.ml
- lib/vcs.mli
- tests/bin/no_doc/run.t
- tests/bin/url-file/run.t
- tests/lib/test_github.ml
Check that the tag is already present on the remote and point to the same rev as the local tag.
Don't try to push it again if that's true.
This fixes issue https://github.com/ocamllabs/dune-release/issues/172
Pushing the tag may fail because the guessed URI may be wrong or git may not have access to keys necessary for authentication.
That can happen when the user have aliases for SSH hosts, when the HTTPs protocol is usually used (the user has no key), when the user don't use command line git, or when `dune-release` is sandboxed.
This allows users to push the tag themselves and continue working with the tool when they encounter issues https://github.com/ocamllabs/dune-release/issues/203 and https://github.com/ocamllabs/dune-release/issues/169
> Distrib: Push the tag only if necessary

- CHANGES.md
- README.md
- lib/vcs.ml
Users who haven't set up ssh will get a Permission denied error from
github when using `dune-release publish`. This commit adds to the README
how the user can configure git in order to solve that problem. It also
adds a hint to the Permission denied error message pointing to that
new part of the README.
Closes #212
> Suggest a solution for users without ssh set up

- CHANGES.md
- bin/bistro.ml
- bin/cli.ml
- bin/cli.mli
- bin/distrib.ml
- bin/distrib.mli
- bin/lint.ml
- bin/opam.ml
- bin/opam.mli
- bin/publish.ml
- bin/publish.mli
- bin/tag.ml
- lib/pkg.ml
- tests/bin/include-versioned-dotfiles/run.t
- tests/bin/tag-2-packages/run.t
This removes option --name from all commands.
This fixes #324, where `dune-release distrib` would fail if a name is not present in `dune-project` (because it calls `dune subst`), therefore rendering pointless any passed --name.
So this pull request takes the brute force approach and removes --name from all commands. The upside is that this is simple, consistent and mostly removes code.
The downsides are:
- it causes a possible regression if people were using --name from other commands than `distrib` (I have no idea if that was useful or actually used ; I believe that for people with only one .opam file there would not have been a reason to use this)
- it removes the documentation for how the distribution is named (longest common prefix of .opam files, first word of main README title) : …
> Remove option --name

- CHANGES.md
- bin/opam.ml
- lib/text.ml
- lib/text.mli
- tests/lib/test_text.ml
> Fix rewriting of github references (#yyy) in changelog

- CHANGES.md
- bin/bistro.ml
I think it's better to return the intermediate non-zero result as soon as it happens so we can have a more precise log, instead of just carrying on and ignoring the returned exit code of each step except the last one like it's currently the case, what do you think?
Actually some of dune-release steps could return unit instead of a return code but we can keep it like this for now in case we need these exit codes in the future. But personally I would replace these by unit, and use a sum/variant type instead.
> Make the automatic dune-release workflow to stop if a step exits with a non-zero code

- CHANGES.md
- lib/github.ml
- tests/lib/test_github.ml
Fix #312 
This is a temporary solution before something like #215 gets merged.
> Support 'git://' scheme for dev-repo uri

- CHANGES.md
- lib/curl.ml
- tests/bin/url-file/run.t
- tests/lib/test_curl.ml
Fixes #337 
We used to rely on github's default name but it appears it changed recently. Setting this explicitly seems like the right thing to do.
@gpetiot you'll probably have to rebase #271 on top of this, in particular `tag_name` and `name` will obviously have different values, `name` being the actual version while `tag_name`will need to be sanitized in the same way the tag is!
> Fix release names

- CHANGES.md
- bin/opam.ml
- bin/tag.ml
- lib/curl.ml
- lib/curl.mli
- lib/github.ml
- lib/github.mli
- lib/opam.ml
- lib/opam.mli
- lib/pkg.ml
- lib/pkg.mli
- lib/text.mli
- lib/vcs.ml
- lib/vcs.mli
- tests/bin/invalid-version-number/dune
- tests/bin/invalid-version-number/run.t
- tests/lib/test_curl.ml
- tests/lib/test_sos.ml
- tests/lib/test_vcs.ml
- tests/lib/tests.ml
> Sanitize git branch names

- CHANGES.md
- lib/curl.ml
- lib/curl.mli
- lib/github.ml
This PR is built on top of https://github.com/ocamllabs/dune-release/pull/219 by @julow which allows for git tags to not be created if they already exist. This PR takes a notch further and does not create a github release if it already exists.
This might be useful for people who want custom github releases messages or something and still want to use dune-release for the rest. It might also be useful for people who, like myself, are too used to `opam-publish` and already created a tag and release before calling `dune-release`.
People might also be in the same situation if something did not work when they used `opam-publish`, then tries to use `dune-release` instead but the workflow is too different for them and they give up (either give up using opam altogether or release by hand).
I hope …
> Create github releases only if necessary

- CHANGES.md
- bin/opam.ml
- lib/config.ml
- lib/github.ml
- lib/lint.ml
- lib/pkg.ml
- lib/pkg.mli
- tests/bin/non-github-doc-uri/run.t
- tests/bin/non-github-uri/run.t
This commit fixes the following two minor bugs in the workflow of inferring the user name and repo from the opam file fields `homepage` or `dev-repo`.
- It adds a test case for the case the user puts a local path or an empty string into the opam file fields. Before the commit, if the user did so, the first two directories of the corresponding absolute path got inferred as user and repo.
- Before this commit, the uri's in `homemapge` and `dev-repo` fields were transformed into the corresponding uri's to the distribution by appending "releases/download/{version}/{project name}-{version}.tbz" to them. From these distribution uri's, user name and repo were inferred. 
Example: if the uri in the opam file fields was "https://foo.com/", then the process of inferring user name and repo would not …
> Fix the process of inferring user name and repo

- CHANGES.md
- tests/bin/delegate_info/run.t
- tests/bin/distrib-name/run.t
- tests/bin/errors/run.t
- tests/bin/include-submodules/run.t
- tests/bin/include-versioned-dotfiles/run.t
- tests/bin/invalid-version-number/run.t
- tests/bin/no_doc/run.t
- tests/bin/non-github-doc-uri/run.t
- tests/bin/non-github-uri/run.t
- tests/bin/opam-pkg-distrib-file-opt/run.t
- tests/bin/opam-pkg-distrib-uri-opt/run.t
- tests/bin/tag-2-packages/run.t
- tests/bin/tag/run.t
- tests/bin/url-file/run.t
- tests/bin/x-commit-hash/run.t
* ~~When running git init we pass -b main to set an initial branch
explicitly. This prevents the hint informing you that git is
defaulting to master from being printed when using more recent git
versions.~~
* When running git init we also redirect stderr to /dev/null as
newer versions of git print a hint to stderr if there's no default
main branch name set and it is defaulting to 'master'. An alternative
would be to pass -b, but that is not supported by older git versions
as seen on debian, for example.
* after git init we set user.name and user.email for the repository, so
the tests don't fail if they are executed in an environment without a
global git config (CI, sandboxed build systems, …)
> Make git related tests more robust

- CHANGES.md
- lib/check.ml
- lib/pkg.ml
- lib/pkg.mli
- tests/bin/check/run.t
With this commit, `check` also checks if the dune project contains a name stanza. That's necessary for running `dune subst` when constructing the tarball. It might also become necessary in 2.0.0 to infer the main package name. At the moment, for inferring the main package name it's sufficient.
> Add dune project check

- CHANGES.md
- bin/opam.ml
- lib/deprecate.ml
- lib/deprecate.mli
- lib/lint.ml
- lib/opam.ml
Previously only the support for the opam client was deprecated.
> Deprecate opam file format 1.x support as well

- bin/cli.ml
I wanted to emphasize that this is useful for user that do not release to github and that other users should probably not have to care about it!
> Improve documentation of the --dist-uri option

- bin/undraft.ml
- lib/opam.ml
- lib/opam.mli
We recently introduced a bug that completely broke the command as it wasn't able to properly locate the folder to add to opam-repo for the release.
This was introduced very recently so there's no need for a changelog entry!
> Fix opam submit

- CHANGES.md
- bin/opam.ml
- lib/github.ml
- lib/github.mli
Depends on #358
`dune-release opam submit` used to fail when releasing a package that wasn't hosted on github even though this is not required to go through this step.
One should be able to upload the distrib tarball to a custom place on the web and then still use dune-release to create the opam-repository PR as long as they provide the right informations on the command line.
This PR fixes this by skipping the github specific step that consists of rewriting the PR/issue references to the cross repo reference format in the PR message if neither of the `home` or `dev-repo` fields in the opam file points to github.
While working on this I also discovered there were some inconsistencies in the way the configuration is handled so I will fix them in a subsequent PR.
> Fix opam submit for non gh projects

- CHANGES.md
- bin/bistro.ml
Some of the `opam submit` specific options weren't allowed to be passed to the default command, preventing it from being used for releases to custom repositories among other use cases.
This should help with #362 !
> Add missing options to the bistro command

- bin/bistro.ml
Because of how we rewrote it, it seems that it was evaluating the commands in the wrong order.
> Fix Bistro command

- CHANGES.md
- bin/bistro.ml
- bin/cli.ml
- bin/cli.mli
- bin/opam.ml
- bin/opam.mli
- bin/publish.mli
- bin/undraft.ml
- lib/config.ml
- lib/config.mli
- lib/delegate.ml
- lib/delegate.mli
- lib/github.ml
- lib/github.mli
- tests/bin/draft/run.t
- tests/bin/url-file/run.t
The CLI option and env var used to take path which made them unusable in a CI context. They now take the token value directly.
This also improves how the token is passed around, moving the config reading bits as close to the CLI entry points as possible so the rest of the code doesn't have to deal with this and simply require a mandatory token argument, with the value and not the path.
This finally fixes a bug where the content of token files wasn't always sanitized.
> Improve GH token management

- CHANGES.md
- bin/tag.ml
- tests/bin/tag/run.t
When making a release, the default title dune-release will give it when calling `dune-release tag` is `Distribution <tag>`.
This title will be carried on in the github UI:
However I feel like this is a bit surprising. I feel like "distribution" doesn't quite convey the right meaning and "release" feels more right in the default case.
> Set the default tag message to "Release <tag>" instead of "Distribution <tag>"

- CHANGES.md
- lib/lint.ml
- tests/bin/check/run.t
- tests/bin/no_doc/run.t
- tests/bin/non-github-doc-uri/run.t
- tests/bin/non-github-uri/run.t
- tests/bin/url-file/run.t
- tests/bin/x-commit-hash/run.t
Many packages are simple enough and just have a `synopsis` field, the `description` field is not required if `synopsis` is present.
Furthermore, only `synopsis` is shown during `opam search` or `opam list`.
> Linter: check for synopsis instead of description 

- CHANGES.md
- lib/config.ml
- lib/config.mli
- lib/github.ml
- lib/github_v3_api.ml
- lib/github_v3_api.mli
- tests/bin/draft/run.t
- tests/bin/url-file/run.t
- tests/lib/test_github_v3_api.ml
This changes from using `-u user:token` to authenticate Github v3 API request to using the recommended `-H "Authorization: token <token>"`.
This allows for better interaction with some organization hosted repos and also allow us to drop the user config field which we won't need anymore!
> Use proper token based authentication for github v3 API

- CHANGES.md
- bin/cli.ml
- bin/config.ml
- bin/opam.ml
- bin/undraft.ml
- lib/config.ml
- lib/config.mli
- lib/deprecate.ml
- lib/deprecate.mli
- lib/github.ml
- lib/github.mli
- lib/github_v3_api.ml
- lib/github_v3_api.mli
- lib/prompt.ml
- lib/prompt.mli
- tests/lib/test_github.ml
- tests/lib/test_github_v3_api.ml
This PR deprecates the `user` CLI option and config field.
The value, whether it comes from the CLI or the config is ignored, we rely entirely on remote-repo now.
Deprecation warnings are emitted whenever someone tries to use the CLI option and if they try to read or modify the field via the `config` subcommand.
New configuration will be created without a user field from now on.
I fixed the config creation step as before it would crash if the repo wasn't hosted on github because it was trying to parse the opam files field, looking for a github username to use as a suggestion in the config creation quiz.
There are further things to fix here, in particular, the fact that we still try to create a config even if all the information is provided via the command line. I will take care of this in …
> Deprecate user options and config field and rely on remote-repo entirely

- CHANGES.md
- bin/cli.ml
- bin/cli.mli
- bin/config.ml
- bin/opam.ml
- bin/opam.mli
- bin/undraft.ml
- lib/config.ml
- lib/config.mli
- lib/stdext.ml
- lib/stdext.mli
These options were properly used but they didn't prevent dune-release from accessing the configuration file and eventually, from
creating a new one through interactive prompts. This behaviour prevented it from being used in a CI.
Now the configuration is only looked up (and eventually created) if dune-release doesn't have enough information to proceed with
the release.
In order to fix this I did a few things:
- I made both config fields mandatory, dune-release can't produce a config without those filled up anymore. This used to be pretty much the case but one could manage to do it if they created the config using `dune-release config set`.
- I replaced `Config.v` with an accessor like function, similar to what we use for `keep_v` and `auto_open`. If the CLI provided value is provided, …
> Fix interpretation of --local-repo and --remote-repo

- CHANGES.md
- bin/bistro.ml
- bin/check.ml
- bin/cli.ml
- bin/cli.mli
- bin/distrib.ml
- bin/distrib.mli
- bin/lint.ml
- bin/opam.ml
- bin/opam.mli
- bin/publish.ml
- bin/publish.mli
- bin/undraft.ml
- lib/config.ml
- lib/config.mli
- lib/delegate.ml
- lib/delegate.mli
This PR adds the missing `--no-auto-open` flag to the default command.
It also slightly improves the handling of config CLI arguments, i.e. CLI args that are meant to override or replace values that might be present in the user's config file. The correspongind cmdliner terms now wrap `'a Config.Cli.t` values, which have to be passed to the corresponding `Config` functions in order to extract a usable value out of them. This module now centralizes the logic responsible for selecting the right value based on what was passed on the command line and what is present in the config.
> Add --no-auto-open to default command and improve config CLI args mgmt

- bin/check.ml
The short name wasn't valid as it was longer than one character. We only have the long name now!
> Fix --working-tree option

- .ocamlformat
- bin/help.ml
This is a preview of the not-yet-released `ocamlformat.0.19.0`, please wait until the package is published in opam to merge this PR. The output is still likely to slightly change before the package is released.
> Upgrade to ocamlformat.0.19.0

- CHANGES.md
- bin/cli.ml
Cmdliner accepts everything that is longer than one character as a long option, hence it made `-V` into `---V` long option.
This has been broken since `-V` was added in https://github.com/ocamllabs/dune-release/commit/809f5391dad64c32d381c550dc56ec4233336b1a, so maybe nobody uses it and it might sense to just remove that option?
> Fix `---V` to be `-V`

- lib/vcs.ml
- tests/bin/distrib-name/run.t
- tests/bin/draft/run.t
- tests/bin/invalid-version-number/run.t
- tests/bin/non-github-doc-uri/run.t
- tests/bin/non-github-uri/run.t
- tests/bin/url-file/run.t
- tests/bin/x-commit-hash/run.t
The code just checked the ref to exist which checked whether the ref existed. When passing in an (existing) commit hash this would return true, because a commit hash is a valid ref, but it is not a tag. This changes the code so it actually tests that the passed reference is indeed a tag.
I ran across this as I was accidentally passing commithashes to it (since the tagging failed) and it still accepted them.
This is not a user visible change, so I'm not adding this to the changelog, this is purely about correctness of the code.
> Check for the tag to be a tag, not just a valid ref

- CHANGES.md
- bin/opam.ml
- bin/undraft.ml
- lib/pkg.ml
- lib/pkg.mli
- lib/vcs.ml
- lib/vcs.mli
- lib/version.ml
- lib/version.mli
- tests/bin/invalid-version-number/run.t
- tests/bin/version-from-tag/dune
- tests/bin/version-from-tag/run.t
- tests/lib/test_pkg.ml
- tests/lib/test_vcs.ml
This changes the source from where to read the version from the changelog to the tag. To be able to serialize typical versions into git tags it uses a simplified convention of [DEP-14](https://dep-team.pages.debian.net/deps/dep14/): `~` becomes `_` and vice versa.
Checking opam-repository for "exotic" versions with
```sh
fd --type d '.+\..+' | rg '\.(.+)' --replace '$1' --only-matching | rg '[^-\.\d\w+~]''
```
Yields that once dots, digits, letters, `-`, `+` and `~` are excluded, there are no other surprising characters that we need to be careful in practice.
This also allows users of `dune-release` that aren't using the changelog file as source of truth use the tool and even maps tags like `1.3_beta3` into OPAM compatible `1.3~beta3` which could be quite useful.
Fixes #381
> Infer version from tag

- dune-project
- dune-release.opam
- lib/config.ml
- lib/dune
- lib/stdext.ml
- lib/stdext.mli
We concluded that YAML support is not something that we want to have since nobody actually likes the YAML format and creating a YAML parser is sufficiently difficult that the only good library for it uses ctypes to bind to libyaml. A more realistic alternative is switching the configuration to use s-expressions and use a proper s-expression parser in the medium term since we will need this to parse `dune-project` files anyway and this way we avoid the proliferation of various ad-hoc config files in the OCaml ecosystem.
This reverts commit 901a95402dc534b1cd067d51b68ffb1f64406aa6, reversing changes made to cee97c1235aadacd24474d798f4ba2ee6e1a4d0e.
> Revert use-yaml branch merge

- CHANGES.md
- lib/github.ml
- lib/github_v3_api.ml
- lib/github_v3_api.mli
After we implemented #386 to distinguish between a project version and a VCS tag it became pretty clear that the github release logic was using the wrong one. This PR uses the tag now.
Or in [meme form](https://twitter.com/godtributes): TAGS FOR THE TAG GOD
> Use the VCS tag instead of the version to create releases

- dune-project
- dune-release.opam
- lib/dune
The module `OpamParserTypes.FullPos` is from ocaml-file-format and if too low of a version is selected ([like `2.0.0~rc2` by the OCaml CI](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/b6acd886778d49581c876692880f381ddd813cd0/variant/opam-2.1,compilers,4.06,dune-release.1.5.2,lower-bounds)) as a dependency of `opam-format` then the build will fail.
Therefore we need `opam-file-format` as direct dependency.
> Add dependency to `opam-file-format`

- tests/bin/version-from-tag/run.t
The ancient git version in CentOS 7 (1.8.3.1) has a but where despite `--allow-empty-message` it will not accept `-m ''` so to fix this we set a (boring) message to commit.
> Specify a message in the git tests

- tests/bin/opam-pkg-distrib-multiple/run.t
- tests/bin/version-from-tag/run.t
Similar regression as also fixed in #334: We need to ensure that the git user's name and email are set, otherwise we can't create a commit if no global git configuration has been set up.
> tests: ensure user.email and user.name is always set to allow commiting

- CHANGES.md
- lib/text.ml
- tests/lib/test_text.ml
I recently started using the change log format specified in https://keepachangelog.com. This format uses "Changelog" as the first level of header.
This resulted in `dune-release` trying to use `"Changelog"` as the tag. I manually specified the tag, but then `dune-release` used the entire changelog for the pull-request message, see https://github.com/ocaml/opam-repository/pull/20195.
This PR changes `Text.change_log_last_entry` to recurse into `changes` if the header title is "Changelog", and drops brackets around version numbers if there are any.
Btw, I wasn't sure if PRs from outsiders are welcome or not and I didn't find a contribution guide. Hope this doesn't feel too aggressive since I didn't open an issue first.
> Parse change logs in the style of keepachangelog.com

- bin/distrib.ml
- tests/bin/distrib-name/run.t
Fixes #443 
The message was a bit confusing and could lead people to believe those changes could end up in the archive whereas it was trying to warn them of the opposite.
> Improve `distrib` dirty repo warning message

- CHANGES.md
- lib/dune
- lib/pkg.ml
- lib/pkg.mli
- tests/lib/test_pkg.ml
The current parsing code looks for `(name X)` on all lines of `dune-project`, and returns the last one that matches. This can return the wrong value when opam file generation is used, for example:
(lang dune 2.4)
(name main)
(generate_opam_files true)
(package
(name main))
(package
(name other))
In this case, the project name is parsed as `other`.
This PR fixes it by only looking at the beginning of the line and returning the first match. It also uses `Re` (already used) instead of direct string manipulation.
> Fix dune-project name parsing

- CHANGES.md
- lib/dune
- lib/pkg.ml
- lib/pkg.mli
- tests/lib/test_pkg.ml
Backport of @emillon 's #445 onto a (newly created) `1.6.x` maintenance branch.
> `dune-project` name parsing backport

- CHANGES.md
- lib/vcs.ml
- tests/bin/tag/run.t
> Avoid collision between branch and tag name

- README.md
- dune-project
- dune-release.opam
- lib/vcs.ml
- tests/lib/test_github.ml
The old URLs should continue working and not all the changes were necessary, but it's nice to keep things updated.
> Repo was moved, update URLs

- CHANGES.md
- bin/check.ml
- bin/cli.ml
- bin/cli.mli
- lib/check.ml
- lib/check.mli
- tests/bin/check/run.t
I found that a project where `dune-release check` succeeded didn't publish because its change log failed to parse, and iterating on debugging and fixing the change log was difficult with no simple way to exercise the change log parsing logic.
> Add flag to `dune-release check` that attempts to discover and parse the change log

- lib/config.ml
This is unused, as well as the associated cleanup function.
> Remove unused reset_terminal hook

- dune-project
- dune-release.opam
Some packages pull in `result` as transitive dependency, resulting in `Result` being not the Stdlib one but one that does not feature `Result.is_ok` if the `result` package is too old.
Given we do not have a direct dependency this is added as a conflict, so if our transitive dependencies drop `result` this problem should go away without introducing spurious dependendencies.
`result.1.5` fixes the issue by passing through `Result` from `Stdlib` on OCaml 4.08+ (which is our minimal supported version).
> Conflict with old version of `result`

- dune-project
- dune-release.opam
We use `Rresult.R.failwith_error_msg` which has been added in 0.6.0.
> opam: fix lower bounds

- CHANGES.md
- bin/opam.ml
- lib/github.ml
- lib/github.mli
- lib/opam.ml
- lib/opam.mli
- lib/pkg.ml
- lib/pkg.mli
- tests/lib/test_github.ml
- tests/lib/test_pkg.ml
If we're submitting a PR for several packages, this uses "project name (N packages)" as PR title, and the project name is used for the branch.
Previously the branch was taken from the shortest package name.
> Use project name for PR title and branch

- CHANGES.md
- dune-project
- dune-release.opam
- lib/pkg.ml
- tests/bin/opam-file-locations/dune
- tests/bin/opam-file-locations/run.t
This requires the as of now not yet released dune 3.8, hence a draft. CI will most likely fail the test.
> Implement support for OPAM files in `opam/` folder

- tests/bin/opam-file-locations/run.t
Turns out only this test was failing because the other tests had this line already, presumably because someone ran the tests on macOS before.
Creating this as PR to make ocaml-ci run it as well and confirm it fixes the issue.
> Fix the tests on macOS

- CHANGES.md
- bin/opam.ml
- bin/undraft.ml
- lib/config.ml
- lib/config.mli
- lib/stdext.ml
- lib/stdext.mli
This is an attempt at fixing https://github.com/tarides/dune-release/issues/479 but I noticed that the `user` option is deprecated.
Decoding the remote URL can easily fail, instead let the user provide the correct username to use in API calls.
Only attempt to decode the remote URL if the `user` option is not set. The error message is changed to encourage setting the `user` option instead of asking users to change their URLs.
> Opam: Use the 'user' option as the fork owner

- dune-project
- dune-release.opam
- tests/bin/distrib-name/run.t
dune.3.14.0 adds a loc in its output, see ocaml/dune#9851.
This updates the test output and the constraint.
> Update tests for dune 3.14

- CHANGES.md
- lib/config.ml
Currently, it systematically fails:
```shell
$ dune-release 
[-] Upgrading configuration files: /home/foo/.dune => /home/foo/.config/dune
dune-release: [ERROR] move /home/foo/.dune to /home/foo/.config/dune/release.yml: Destination exists
```
when using dune package management, due to dune getting installed to
~/.dune/bin/dune.
Considering that:
- the migration code from 2018
- it doesn't work at all, since aside from failing unnecessarily, it would
also mess things up by renaming the directory ~/.dune to
~/.config/dune/dune/release.yml
I see no reason to salvage this code.
The second commit cleans up some Result.t that have become infallible.
> drop migration path for the config file

- CHANGES.md
- bin/bistro.ml
- bin/cli.ml
- bin/cli.mli
- bin/publish.ml
- bin/publish.mli
- lib/github.ml
- lib/github.mli
This is useful for private projects where it's (sometimes) unclear what's the dev-repo field should look like (and sometimes `dune` will not generate the right one)
> Allow to overwrite the dev-repo field when creating a GH tag/release

- bin/publish.ml
This is a small fix in the help of the `dune-release publish` command.
Recently the command was updated to remove the ability to publish the documentation, but the `--help` of the command still mentions about publishing the documentation. This PR removes that part.
I noticed this while upgrading to the new dune-release. Thanks!
> Fix publish help - no longer publish the doc
