tarides/dune-release

bin/publish.ml, lib/pkg.ml
=> Pass -p <package> to jbuilder

lib/distrib.ml
=> Fix a bug in Distrib.write_subst

bin/jbuild, bin/opam.ml, dune-release.opam
=> publish: rewrite github references in the submit messages

bin/opam.ml, lib/config.ml, lib/xdg.ml, lib/xdg.mli
=> Store config files in ~/.config/dune

bin/publish.ml
=> doc: copy the _html subdirectory when it exists

bin/publish.ml
=> Really fix the _html/_doc issue

README.md, bin/help.ml, bin/publish.ml, lib/delegate.ml, lib/delegate.mli, lib/github.ml, lib/pkg.ml, lib/pkg.mli, lib/sos.ml, lib/sos.mli
=> Re-add the publish delegates and alt distribution sources

lib/config.ml, lib/opam.ml
The implementation is crude, you might want to revisit the code.
Changes:
1) bug fix, `drop_initial_v` in `opam publish` too (the third copy of this code after distrib.ml and pkg.ml)
2) ux improvement, basic token validation
3) ux improvement(?), echo token on stdin when copying it. I don't think this is critical for security, I am curious what your opinion is :)
=> A few bug-fixes/improvements

lib/pkg.ml
=> Sligthly better delegate heuristics

lib/pkg.ml
=> Improve heuristic to guess the package main name

CHANGES.md, bin/help.ml, bin/opam.ml, lib/config.ml
Small fixes to improve the experience related in #39
=> Improve submit workflow

lib/config.ml
=> Fix configuration upgrade

lib/pkg.ml
=> Fix distrib archive name with distrib_file is provided

lib/pkg.ml
=> be flexible with file names

bin/dune, bin/opam.ml, dune-release.opam
Also support release of 2.0 packages
=> Fix 2.0 format upgrade

dune-project
Signed-off-by: Rudi Grinberg <rudi.grinberg@gmail.com>
=> Add project name to dune-release

bin/distrib.ml, bin/opam.ml, bin/publish.ml, lib/pkg.ml, lib/pkg.mli
=> Fix publishing doc for multiple packages

lib/github.ml, lib/pkg.ml, tests/test_github.ml, tests/test_tags.ml
=> Fix distrib uri when homepage is using github.io

bin/lint.ml, lib/opam.ml, lib/pkg.ml
=> Ensure that a description and a synopsis exist in opam2 files

lib/github.ml, lib/sos.ml, lib/sos.mli
=> Fix doc generation

bin/tag.ml
This PR adds some extra logs to the `tag` command to describe the tag selection steps as it goes.
This is the first step in an effort to try and make `dune-release` output a bit more descriptive for the end users. I decided to tackle the simplest command first, I'll open separate PRs for the others.
=> Add logs to describe the tag command behaviour

bin/publish.ml, lib/delegate.ml, lib/github.ml, lib/sos.ml, lib/sos.mli, lib/styled_pp.ml, lib/styled_pp.mli
This PR adds some app level logs to describe what's going on during a `publish` run.
=> Add logs to describe the publish command behaviour

lib/sos.ml
=> Refactor Sos.cp to use Bos.Cmd.on

lib/github.ml
I though I had silenced those in #137 but I must have failed a rebase somewhere.
=> Silence some git command's output

CHANGES.md, bin/cli.ml, bin/cli.mli, bin/opam.ml, bin/publish.ml, bin/tag.ml, lib/delegate.ml, lib/delegate.mli, lib/github.ml, lib/github.mli, lib/prompt.ml, lib/text.ml, lib/text.mli, lib/vcs.ml
This PR cleans up a few things, improve the logs in some places and add prompts before critical actions.
=> Add more prompts

.travis.yml
This adds travis checks for newer versions of OCaml!
=> Upgrade CI scripts

bin/help.ml, bin/tag.ml, lib/text.mli
=> Remove documentation of removed dune-release-log subcommand

CHANGES.md, lib/archive.ml, lib/pkg.ml, lib/stdext.ml, lib/stdext.mli, tests/alcotest_ext.ml, tests/alcotest_ext.mli, tests/test_stdext.ml, tests/tests.ml
Fix #167 (a bit complicated to add tests for Pkg for now)
=> Ignore backup files when looking for README, CHANGES and LICENSE files

bin/bistro.ml, bin/distrib.ml, bin/distrib.mli, bin/opam.ml, bin/opam.mli, bin/publish.ml, bin/publish.mli
Fix #187 
Documentation will be formatted after #198
=> Add subcommands API to be called by bistro

.ocamlformat, lib/archive.ml, lib/opam.ml
There's only two places where formatting differs and those are bug fixes so let's upgrade!
=> Upgrade to ocamlformat 0.13.0

CHANGES.md, dune-release.opam, lib/curl.ml, lib/curl.mli, lib/dune, lib/github.ml, lib/sos.mli, tests/alcotest_ext.ml, tests/alcotest_ext.mli, tests/test_curl.ml
I need to run some tests and then we could see if we can remove some options and simplify this code.
=> Use Curly instead of Cmd to interact with github

CHANGES.md, bin/tag.ml, lib/prompt.ml, lib/prompt.mli, lib/vcs.ml, lib/vcs.mli, tests/bin/tag/dune, tests/bin/tag/run.t
=> Command `tag`: improve error and status messages

bin/opam.ml, bin/tag.ml, lib/github.ml, lib/prompt.ml, lib/prompt.mli
I'm just restructuring the confirm_and_abort for negative default behavior according to @gpetiot 's suggestion in #231.
=> Fuse confirm_and_abort_neg into confirm_and_abort

.ocamlformat
=> Upgrade to ocamlformat.0.14.2

lib/github.ml
To avoid having our github tokens revoked by github if they are leaked by the test logs.
=> Anonymize token so it is not shown in --dry-run log

tests/bin/non-github-doc-uri/dune, tests/bin/non-github-doc-uri/run.t, tests/bin/non-github-uri/dune, tests/bin/non-github-uri/run.t
One test where the publication of the doc fails, one where the publication of the distrib fails.
=> Test release process for non-github URIs

CHANGES.md, lib/pkg.ml, tests/bin/no_doc/run.t
this is making the tests more deterministic
also fix #249
=> Define the order of packages

CHANGES.md, bin/bistro.ml, bin/cli.ml, bin/cli.mli, bin/opam.ml, bin/opam.mli, bin/publish.ml, bin/publish.mli, lib/delegate.ml, lib/delegate.mli, lib/github.ml, lib/github.mli
Fix #273, not sure how to test it yet
=> Add a '--token' option to 'publish' and 'opam' commands to specify a github token

CHANGES.md, lib/pkg.ml, lib/text.ml, lib/text.mli, tests/bin/no_doc/run.t, tests/lib/test_text.ml, tests/lib/tests.ml
=> Improve trimming of the changelog

CHANGES.md, lib/github.ml, lib/opam.ml, lib/vcs.ml, lib/vcs.mli
Fix #253, no diff on the tests so far, maybe we need to add more.
=> Normalize git comands calls and error reporting

CHANGES.md, bin/opam.ml, tests/bin/url-file/dune, tests/bin/url-file/run.t
=> Trim the data of the `url` file before filling the `url.src` field

CHANGES.md, lib/github_v3_api.ml, lib/github_v3_api.mli, lib/json.ml, lib/json.mli, tests/lib/pull_request_response.ml, tests/lib/test_github_v3_api.ml
=> Better report GitHub API errors

CHANGES.md, lib/pkg.ml, tests/bin/tag-2-packages/dune, tests/bin/tag-2-packages/run.t
=> Fix error message when tag cannot guess project name

README.md
Hopefully this (in addition with #325) will help with #320
=> Clarify that uncommitted changes are ignored in distrib

CHANGES.md, lib/vcs.ml, tests/bin/errors/run.t, tests/bin/non-github-doc-uri/run.t, tests/bin/non-github-uri/run.t, tests/bin/url-file/run.t, tests/bin/x-commit-hash/run.t
=> Use the <rev>^0 syntax instead of <rev>^{commit}

bin/opam.ml, lib/config.ml, lib/github.ml, lib/lint.ml, lib/pkg.ml, lib/pkg.mli, lib/stdext.ml, lib/stdext.mli, lib/uri.ml, lib/uri.mli, tests/lib/test_uri.ml, tests/lib/test_uri.mli, tests/lib/tests.ml
=> Clean up pkg.ml and extract a new module Uri

.ocamlformat, bin/help.ml
This is a preview of the not-yet-released ocamlformat.0.17.0, please wait until the package is published in opam to merge this PR.
=> Upgrade to ocamlformat.0.17.0

dune-project, dune-release.opam, lib/config.ml, lib/dune, lib/stdext.ml, lib/stdext.mli
Rewriting the parsing of the release.yml file that was a bit adventurous.
This PR is a reboot of #355 that was deleted (and couldn't bring it back) since the master branch has been renamed.
=> Use yaml library to parse release.yml configuration file

tests/bin/non-github-doc-uri/run.t, tests/bin/non-github-uri/run.t
Experiment on whether we can replace `Logs.on_error_msg` with something that uses our own logging functions and is more consistent. We had some ordering issues so this should help.
=> Consistent error reporting

CHANGES.md, bin/bistro.ml, bin/cli.ml, bin/cli.mli, bin/distrib.ml
Some flags from the distrib command weren't available.
=> Add missing command line flags to main command

CONTRIBUTING.md, README.md
=> Contributor experience improvements

dune-project, dune-release.opam
=> Bump curly dependency to fix PATH issue on some systems

tests/bin/check/run.t
Fixes issue discovered in https://github.com/ocaml/opam-repository/pull/23984
=> Fix test failures when using OPAM 2.2

.git-blame-ignore-revs, .ocamlformat, bin/distrib.ml, bin/opam.ml, lib/check.ml, lib/github.ml, lib/opam.ml, lib/pkg.ml, lib/uri_helpers.mli
Mostly due to the change in indentation of a `let` or `if` inside parentheses.
The aim of this commit is to gather feedback.
Changelog can be found here: https://github.com/ocaml-ppx/ocamlformat/blob/main/CHANGES.md
=> Upgrade to ocamlformat 0.26.0

lib/config.ml
=> fix: use 'paste' instead of 'copy'
